### ISSUE TITLE
system-sdk: I can still see a symlink there

### ISSUE THREAD

**Issue by michal-z** [foxnne/pixi#11]
Looks like there are still some symlinks in `zig-gamedev/libs/macos12`:

For example:
`https://github.com/foxnne/pixi/blob/main/src/deps/zig-gamedev/system-sdk/macos12/System/Library/Frameworks/ApplicationServices.framework/ApplicationServices.tbd`

Please make sure to delete the entire `system-sdk` folder and copy it again from `zig-gamedev`.

**Comment by foxnne** [comment]
Ah thanks. I did delete the entire folder and copy over from zig-gamedev but I guess when I pulled latest from zig-gamedev it didn't delete the old symlinks.

**Comment by foxnne** [comment]
Okay, I had to push removing the entire system-sdk folder to get them out, and then re-add that folder and push that separately for some reason, but they should be gone now. Thanks!

**Comment by michal-z** [comment]
Yes, they are gone it looks fine!
