### ISSUE TITLE
Update to latest `mach-core` and `mach-sysgpu`, and nominated `zig` version

### ISSUE THREAD

**Issue by foxnne** [foxnne/pixi#45]
Currently `mach-core` has disabled `sysgpu` until further notice, which we need for stability on macOS. There is also a crash on build with `sysgpu` enabled on Windows for the version currently used in Pixi.

We will be frozen on this version until `sysgpu` is reenabled in `mach-core`. 

**For now, Windows/Linux users can build and run using `zig build run`, and macOS users can build and run using `zig build run -Duse_sysgpu=true`.**

**Comment by no1hitjam** [comment]
Would it be safe to make contributions on the mach-core branch right now?

**Comment by foxnne** [comment]
Sorry for the confusion! That big PR is now merged, and 'main' is safe for contributions. The only thing we should avoid is changing `mach-core` versions until `sysgpu` is re-enabled. Once that happens I'll update everything to latest. :)
