### ISSUE TITLE
Pinch to zoom

### ISSUE THREAD

**Issue by alterae** [foxnne/pixi#63]
When using a trackpad, it would be nice to have the ability to zoom in and out with a pinch gesture, like in many other programs.
No clue how easy or hard this would be to implement, though.

**Comment by foxnne** [comment]
I believe what this comes down to is support built into GLFW and currently GLFW doesn't have any support for pinch gestures. 

@slimsag would know more I'm sure, but as mach will be moving away from GLFW there's a chance that at least on macOS or certain platforms that pinch gestures could be supported in the future, but I think it will be a while before we end up getting to something like that.

**Comment by foxnne** [comment]
Pinch to zoom is supported now, and correctly offsets camera location based on mouse pointer location
