### ISSUE TITLE
Linux/Wayland/Xorg: HotKeys Modifiers Not Registering Properly

### ISSUE THREAD

**Issue by verdude** [foxnne/pixi#65]
When trying to create a new animation, the `.left_control` modifier isn’t registering as `.pressed`, making it difficult to trigger certain hotkeys as intended.

The issue is reproducible on wayland and x11, and modifying Hotkeys.zig with the following changes appears to resolve it:
```
diff --git a/src/input/Hotkeys.zig b/src/input/Hotkeys.zig
index 8f9fd59..6366c08 100644
--- a/src/input/Hotkeys.zig
+++ b/src/input/Hotkeys.zig
@@ -127,14 +127,12 @@ pub fn setHotkeyState(self: *Self, k: Key, mods: Mods, state: KeyState) void {
                     .release => false,
                     else => true,
                 };
-            } else if (hk.mods) |md| {
-                if (@as(u8, @bitCast(md)) == @as(u8, @bitCast(mods))) {
-                    hk.previous_state = hk.state;
-                    hk.state = switch (state) {
-                        .release => false,
-                        else => true,
-                    };
-                }
+            } else if (hk.mods) |_| {
+                hk.previous_state = hk.state;
+                hk.state = switch (state) {
+                    .release => false,
+                    else => true,
+                };
             }
         }
     }
```
I’m not fully certain of the purpose of `hotkey.mods`—`.left_control` itself is a modifier—so this change might not be entirely valid. I’m also unsure if it could interfere with other functionality. Either way, I hope it helps pinpoint the issue here.

Debug Logs: When debugging, I found that Mach appears to set the modifiers as follows:

    Expected: { .shift = false, .control = true, .alt = false, .super = false, .caps_lock = false, .num_lock = false }
    Actual: { .shift = false, .control = false, .alt = false, .super = false, .caps_lock = false, .num_lock = false }

Question: Is this an issue with mach or pixi? If it’s specific to mach/Wayland, do you think it’s worth addressing given the project isn’t aligned with mach’s master?

It seems like the modifier is expected (by pixi) to be set by mach here: https://github.com/hexops/mach/blob/b72f0e11b6d292c2b60789359a61f7ee6d7dc371/src/core/platform/wayland/Core.zig#L704

Let me know if I can provide additional information to clarify or assist with reproducing the issue. Thank you for your time!

**Comment by foxnne** [comment]
Thanks for your writeup! I'm interested in why casting both mods to a u8 and comparing them fails on Wayland and x11, if that's the only thing causing the issue. 

Anyway, to the issue, I think that since pretty soon mach will be reworking all windowing and input and likely none of this will be applicable that we can just rework the hotkey comparison. I'll try to take a look at this either tonight or tomorrow, but I don't have a machine to test it on.

**Comment by verdude** [comment]
If I understand correctly, it seems like the casting is working but mach is not setting the `.control` modifier.

So I guess it is probably a mach issue?

**Comment by verdude** [comment]
I patched and compiled with the edit and nothing else seems to have broken so it serves its purpose :)

I appreciate you sharing your work on pixi and other projects, they are very helpful
