### ISSUE TITLE
crash upon value change, animation

### ISSUE THREAD

**Issue by theoteno** [foxnne/pixi#7]
Changing the starting and total frame number exits the program.

**Comment by foxnne** [comment]
Thank you for the issues! I'm currently rewriting the entire program based on changes I feel will make it more useful for me on my own projects having used the current version. It was also incredibly buggy, it was my first real program to try to write using Zig so hopefully this time around I can make better decisions and produce something a little more solid. 

Appreciate it!

**Comment by foxnne** [comment]
Closing because we are undergoing a full rewrite.
